import Header from './header/header.component';
import TotalSum from './total-sum/total-sum.component';
import Table from './table/table.component';
import TableTest from './table-test/table.component';
import TableSt from './table-st/table-st.component';

export default angular.module('app.shared.components', [
    Header,
    TotalSum,
    Table,
    TableTest,
    TableSt
])
    .name;


const a = {
    'questionId': 20641,
    'controlAreaId': 11,
    'ctrlAreaName': 'Overall Program Management, Policy and Governance',
    'qnrId': null,
    'ddqId': 202,
    'title': 'Question 2',
    'clientId': 0,
    'description': 'What is the frequency your policy is reviewed / updated?  If Ad hoc, please describe in the comments section.',
    'widgetType': 'MULTI_CHOICE_SINGLE',
    'status': 'NOT_STARTED',
    'hasChild': false,
    'parentId': 0,
    'createdOn': null,
    'createdBy': null,
    'modifiedOn': null,
    'modifiedBy': null,
    'modifiedById': null,
    'hint': null,
    'required': true,
    'requiredDoc': false,
    'docEligible': 'YES',
    'displaySeq': 3,
    'helpText': null,
    'shortForm': true,
    'version': null,
    'disabled': false,
    'widgetValues': [{
        'widgetId': 21149,
        'questionId': 20641,
        'value': '0-6 Months',
        'displayValue': null,
        'hint': null,
        'seq': 0,
        'hasComment': false,
        'riskWidgetScore': {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21149,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        },
        'changed': false,
        'links': []
    }, {
        'widgetId': 21150,
        'questionId': 20641,
        'value': '7-12 Months',
        'displayValue': null,
        'hint': null,
        'seq': 0,
        'hasComment': false,
        'riskWidgetScore': {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21150,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        },
        'changed': false,
        'links': []
    }, {
        'widgetId': 21151,
        'questionId': 20641,
        'value': '13-18 Months',
        'displayValue': null,
        'hint': null,
        'seq': 0,
        'hasComment': false,
        'riskWidgetScore': {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21151,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        },
        'changed': false,
        'links': []
    }, {
        'widgetId': 21152,
        'questionId': 20641,
        'value': '19+ Months',
        'displayValue': null,
        'hint': null,
        'seq': 0,
        'hasComment': false,
        'riskWidgetScore': {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21152,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        },
        'changed': false,
        'links': []
    }, {
        'widgetId': 21153,
        'questionId': 20641,
        'value': 'Ad hoc',
        'displayValue': null,
        'hint': null,
        'seq': 0,
        'hasComment': false,
        'riskWidgetScore': {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21153,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        },
        'changed': false,
        'links': []
    }],
    'conditions': [],
    'relatedQuestions': [],
    'answer': {
        'reqQtnTLId': 16992894,
        'reqId': 31979,
        'ctrlInstId': 18736,
        'ctrlAreaId': 11,
        'qId': 20641,
        'modifiedBy': 540,
        'modifiedOn': '2017-12-28 11:59:41.791545',
        'assignedTo': 540,
        'assignedBy': null,
        'lockedBy': null,
        'status': 'NOT_STARTED',
        'comment': null,
        'answerAttachments': [],
        'answerValue': {'value': [{'value': ''}], 'reqQtnTLId': 16992894, 'dirty': true},
        'modifiedbyUser': 'Sandeep srivastava',
        'dcCheckResult': {
            'matchedKeyWords': [],
            'keyWordsCheckStatus': null,
            'manualCheckStatus': null,
            'passiveMandatoryAttach': false
        },
        'changed': null,
        'commentChanged': null,
        'isApplicable': true,
        'isStandardRes': false,
        'isReused': false,
        'dirty': true
    },
    'display': false,
    'lockedBy': null,
    'clientName': null,
    'ctrlstatus': 'IN_PROGRESS_ASSIGNED',
    'assignedTo': 540,
    'assignedToName': 'Sandeep srivastava',
    'assignedToGroup': 0,
    'assignedGroupName': null,
    'productId': null,
    'productName': null,
    'modifiedId': null,
    'answeredQtnCtn': 0,
    'totalQtnCtn': 0,
    'reqId': 31979,
    'reuseAvailable': false,
    'ctrlReuseAvailable': false,
    'countryName': null,
    'countryCode': null,
    'issueDesc': null,
    'answerValueAudit': [],
    'ctrlInstId': 18736,
    'questionSeq': '2',
    'qtnReviewCmtList': [],
    'internalQtnReviewCmtList': [],
    'score': null,
    'avgScore': null,
    'scoreComment': null,
    'scoreModifiedBy': 0,
    'scoreModifiedByName': null,
    'scoreModifiedOn': null,
    'newCommentCnt': 0,
    'totalCommentCnt': 0,
    'gapMarked': false,
    'gapRemediationId': 0,
    'gapRemediationStatus': null,
    'ctrlStatusDispVal': null,
    'riskQuestionScore': {
        'questionScoreId': null,
        'riskScoreTemplateId': null,
        'subCtrlAreaId': 11,
        'questionId': 20641,
        'weight': null,
        'isGapUnanswered': null,
        'gapThresholdCond': null,
        'gapThresholdValue': null,
        'riskWidgetScores': [{
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21149,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        }, {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21150,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        }, {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21151,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        }, {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21152,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        }, {
            'widgetScoreId': null,
            'questionScoreId': null,
            'widgetValueId': 21153,
            'rawScore': null,
            'rawScoreValidationError': null,
            'widgetValue': null
        }],
        'weightValidationError': null,
        'gapValidationError': null,
        'modifiedOn': null,
        'modifiedBy': null,
        'questionWidgetType': null
    },
    'riskScore': {
        'riskCalculatedScore': null,
        'riskOverriddenScore': null,
        'riskOverriddenReason': null,
        'riskOverriddenWeight': null,
        'riskQuestionWeight': null,
        'riskQuestionRawScore': null,
        'overriddenFlag': false
    },
    'used': false,
    'requiredComment': false,
    'mandatoryCommentValue': [],
    'mandatoryDocValue': [],
    'mandatoryCommentDocValue': [],
    'manualDqcCheck': true,
    'notApplicableEligible': true,
    'keyWords': null,
    'dcCheckType': null,
    'minKeyWords': 0,
    'update': false,
    'gapPriority': null,
    'dvScope': false,
    'empty': false,
    'passiveDcCheckStatus': null,
    'links': []
};